########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findut.cmake")
set(ut_FOUND 1)
set(ut_VERSION "1.1.8")

find_package_handle_standard_args(ut REQUIRED_VARS
                                  ut_VERSION VERSION_VAR ut_VERSION)
mark_as_advanced(ut_FOUND ut_VERSION)

set(boost_COMPONENTS boost::ut)

if(ut_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${ut_FIND_COMPONENTS})
        list(FIND boost_COMPONENTS "boost::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'boost'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'boost'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(boost_INCLUDE_DIRS "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_INCLUDE_DIR "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_INCLUDES "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_RES_DIRS )
set(boost_DEFINITIONS )
set(boost_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(boost_COMPILE_DEFINITIONS )
set(boost_COMPILE_OPTIONS_LIST "" "")
set(boost_COMPILE_OPTIONS_C "")
set(boost_COMPILE_OPTIONS_CXX "")
set(boost_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(boost_LIBRARIES "") # Will be filled later
set(boost_LIBS "") # Same as boost_LIBRARIES
set(boost_SYSTEM_LIBS )
set(boost_FRAMEWORK_DIRS )
set(boost_FRAMEWORKS )
set(boost_FRAMEWORKS_FOUND "") # Will be filled later
set(boost_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(boost_FRAMEWORKS_FOUND "${boost_FRAMEWORKS}" "${boost_FRAMEWORK_DIRS}")

mark_as_advanced(boost_INCLUDE_DIRS
                 boost_INCLUDE_DIR
                 boost_INCLUDES
                 boost_DEFINITIONS
                 boost_LINKER_FLAGS_LIST
                 boost_COMPILE_DEFINITIONS
                 boost_COMPILE_OPTIONS_LIST
                 boost_LIBRARIES
                 boost_LIBS
                 boost_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to boost_LIBS and boost_LIBRARY_LIST
set(boost_LIBRARY_LIST )
set(boost_LIB_DIRS )

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_boost_DEPENDENCIES "${boost_FRAMEWORKS_FOUND} ${boost_SYSTEM_LIBS} ")

conan_package_library_targets("${boost_LIBRARY_LIST}"  # libraries
                              "${boost_LIB_DIRS}"      # package_libdir
                              "${_boost_DEPENDENCIES}"  # deps
                              boost_LIBRARIES            # out_libraries
                              boost_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "boost")                                      # package_name

set(boost_LIBS ${boost_LIBRARIES})

foreach(_FRAMEWORK ${boost_FRAMEWORKS_FOUND})
    list(APPEND boost_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND boost_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${boost_SYSTEM_LIBS})
    list(APPEND boost_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND boost_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(boost_LIBRARIES_TARGETS "${boost_LIBRARIES_TARGETS};")
set(boost_LIBRARIES "${boost_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_PREFIX_PATH})


########### COMPONENT ut VARIABLES #############################################

set(boost_ut_INCLUDE_DIRS "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_ut_INCLUDE_DIR "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_ut_INCLUDES "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(boost_ut_LIB_DIRS )
set(boost_ut_RES_DIRS )
set(boost_ut_DEFINITIONS )
set(boost_ut_COMPILE_DEFINITIONS )
set(boost_ut_COMPILE_OPTIONS_C "")
set(boost_ut_COMPILE_OPTIONS_CXX "")
set(boost_ut_LIBS )
set(boost_ut_SYSTEM_LIBS )
set(boost_ut_FRAMEWORK_DIRS )
set(boost_ut_FRAMEWORKS )
set(boost_ut_BUILD_MODULES_PATHS )
set(boost_ut_DEPENDENCIES )
set(boost_ut_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT ut FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(boost_ut_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(boost_ut_FRAMEWORKS_FOUND "${boost_ut_FRAMEWORKS}" "${boost_ut_FRAMEWORK_DIRS}")

set(boost_ut_LIB_TARGETS "")
set(boost_ut_NOT_USED "")
set(boost_ut_LIBS_FRAMEWORKS_DEPS ${boost_ut_FRAMEWORKS_FOUND} ${boost_ut_SYSTEM_LIBS} ${boost_ut_DEPENDENCIES})
conan_package_library_targets("${boost_ut_LIBS}"
                              "${boost_ut_LIB_DIRS}"
                              "${boost_ut_LIBS_FRAMEWORKS_DEPS}"
                              boost_ut_NOT_USED
                              boost_ut_LIB_TARGETS
                              ""
                              "boost_ut")

set(boost_ut_LINK_LIBS ${boost_ut_LIB_TARGETS} ${boost_ut_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/sarah/.conan/data/boost-ext-ut/1.1.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT ut TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET boost::ut)
        add_library(boost::ut INTERFACE IMPORTED)
        set_target_properties(boost::ut PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${boost_ut_INCLUDE_DIRS}")
        set_target_properties(boost::ut PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${boost_ut_LIB_DIRS}")
        set_target_properties(boost::ut PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${boost_ut_LINK_LIBS};${boost_ut_LINKER_FLAGS_LIST}")
        set_target_properties(boost::ut PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${boost_ut_COMPILE_DEFINITIONS}")
        set_target_properties(boost::ut PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${boost_ut_COMPILE_OPTIONS_C};${boost_ut_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET boost::boost)
        add_library(boost::boost INTERFACE IMPORTED)
    endif()
    set_property(TARGET boost::boost APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${boost_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT ut BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${boost_ut_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
